### ISSUE TITLE
Technical Specifications V1

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-3-virtual-processor-team-1#13]
### Description

Proofreading the technical specifications:
— Glossary:
    — Standard libraries
   — GCC
   — top-down
   — AST
   — Virtual Machine
   — CPU
   — registers 

— Syntax:
    — “The project is divided into a virtual processor and an interpreter” → l.82
    — "type  and" | two spaces → l.270
    — Words and verbs in US English instead of UK English | "neighboring", "neighbor", "tokenized",...

### Severity

2 - High

### Version

V1

### System informations

Operating system: MacOs

### Potential solution

Add these words to the glossary.
Change the verbs and words in US English to UK English.

### CheckList

- [X] I have checked that the problem has not already been reported.
- [X] I have checked that the problem has not been resolved in the latest version.
- [X] I have mentioned the operating system and compiler used.

**Comment by thomas-planchard** [comment]
Done ✅
