### ISSUE TITLE
issues operations [2024/02/20] 

### ISSUE THREAD

**Issue by NanaChocolat** [algosup/2023-2024-project-3-virtual-processor-team-1#28]
### Description

There are some issues when we want to do operations :
1. Float numbers are not taken into account  `TOKEN ("IMMEDIATE", "#1,3", 1, 3)`.
2. For all the operations, overflow issues is not taken into account.
3. No error message when we put to much too many parameters `ADD R1, #2, #5`.
4. For ADD/SUB/DIV/MUL: no error message when we try to do an operation between an immediate with a string even if, the string is stored before, into a register.
4. For ADD/SUB/DIV/MUL: no error message when we try to do an operation between an address register and a register. 
5. For DIV: no error message when we try to divide by zero even if the zero is stored into a register.
6. MOV: when we don't put the last `"`, all the line is taken as a void 

### Severity

1 - Critical

### System informations

Operating system: Windows

### Expected result

1. Message for the float: `Error Line number of the error + Code on the line + The language does not take floats into account.`
2. Message for the overflow: `Error Line number of the error + Code on the line + Overflow error The program was halted due to an overflow.`
3. Message for too many parameters: `Line number of the error + Code on the line + Too many parameters have been added. Syntax should be : ARGUMENT PARAM1, PARAM2`
4. Message when we try to do an operation whit a "string" and with an address register: `Line number of the error + Code on the line + The operands are not of the same type.`
5. Message for divide by zero: `Line number of the error + Code on the line + It is impossible to divide by 0.`

### Actual result

6. When we wrote:
`MOV R1, "str`
We obtain:
```
 Token("VOID", "VOID", 1, 1)
  Token("VOID", "VOID", 1, 2)
  Token("VOID", "VOID", 1, 3)
```

### CheckList

- [X] I have checked that the problem has not already been reported.
- [X] I have checked that the problem has not been resolved in the latest version.
- [X] I have mentioned the operating system and compiler used.

**Comment by AlexisLasselin** [comment]
Error 1 solved;
Error 2, 4, 6 cannot be solved here

**Comment by AlexisLasselin** [comment]
Error 5 isn't an error

**Comment by AlexisLasselin** [comment]
Error 7 done

**Comment by AlexisLasselin** [comment]
Error 1 solved here, commit: 94d0439311b0bda7486ea971bd7fd2bede75964a
Error 7 here, commit: 61786278c2f73f6d4bd0a1bb5f06564d81a11bf6

**Comment by NanaChocolat** [comment]
Everything is resolved, good work !

**Comment by AlexisLasselin** [comment]
Error 3 solved here:
411f3687ec2d7ef6002df3dd229d14d2d2449acb

**Comment by NanaChocolat** [comment]
This issues is solved, great job !
