### ISSUE TITLE
Documentation issues - Functional specification [2024/01/25] 

### ISSUE THREAD

**Issue by NanaChocolat** [algosup/2023-2024-project-3-virtual-processor-team-1#9]
### Description

#5  Documentation issues - Functional specification [2024/01/25] 

There are a few syntax rule errors:

You have to respect the structure of the titles in the table of contents and in the entire document, especially the small titles: it should be like that : 
- 1.2 Small title and 1. Small title 

Not like that :
- 1.2. Small Title.

You should add a part where you specify that you must put the # in front of whole numbers and don't forget the " " for strings. You could add it in all the "What not to do:" section into 2. Operands.

And there's an error in the MOV section :
You say : "MOV DESTINATION represents the location where the result of **the division** will be stored (the DESTINATION is always a register)." 
Modify it by "MOV DESTINATION represents the location where the result of **the copy** will be stored (the DESTINATION is always a register)."

Also some miss some # in this sections :
- 5.1 DVI (define variable integer) 

### Severity

2 - High

### System informations

Operating system: Windows

### CheckList

- [X] I have checked that the problem has not already been reported.
- [X] I have checked that the problem has not been resolved in the latest version.
- [X] I have mentioned the operating system and compiler used.

**Comment by HiNett** [comment]
Hello @NanaChocolat,
I've made the necessary changes.
I'll let you check, and if everything's fine, I'll let you close the issue.
Thank you

**Comment by NanaChocolat** [comment]
It's good now !
Thank you
